version: '3.8'

services:
  api-gateway:
    image: nginx:latest
    container_name: api-gateway
    volumes:
      - /home/xusandev/Desktop/iouniverse/infrastructure/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    depends_on:
      - camera-service
      - identity
      - rabbitmq

  camera-service:
    build:
      context: ../camera-service
    container_name: camera-service
    ports:
      - "8001:8001"

  identity:
    build:
      context: ../identity
    container_name: identity
    ports:
      - "8002:8002"


  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"    # AMQP port
      - "15672:15672"  # Web UI port
